import './index.css'
const Home = () =>{

    return(
        <div className="a4-page">
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
         <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
         <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
         <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
         <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
         <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
         <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
         <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
         <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
         <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
         <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
         <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        
        </div>
    )
}

export default Home;