import styles from './index.module.css'
import './index.css'
const CoverLetter = () => {
    return (
        <div className="page">
            <section className="page-content no-break-inside">
               <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
         <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
         <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
         <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
         <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
         <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
         <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
         <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
         <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
         <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
         <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
         <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
         <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
         <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
         <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
         <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        <p>Large text can make a design more visually striking and memorable. It stands out against the background, capturing attention and making your content more impactful. This visual appeal can enhance brand recognition and recall.</p>
        

            </section>
        </div>
    )
}

export default CoverLetter;